import { Inter } from 'next/font/google'
import Script from 'next/script'

import ConfirmDialog from '@/components/confirm-dialog'
import Toast from '@/components/toast'

import { ConfirmDialogContextProvider } from '@/context/confirm-context'
import { NextAuthProvider } from '@/context/next-auth-context'
import NUIProvider from '@/context/next-ui-context'
import { SidebarContextProvider } from '@/context/sidebar-context'
import { ToastContextProvider } from '@/context/toast-context'

import type { Metadata } from 'next'

import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: ' Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <head>
        <Script
          src="https://unpkg.com/@phosphor-icons/web"
          strategy="beforeInteractive"
        />
      </head>
      <body className={inter.className}>
        <NextAuthProvider>
          <NUIProvider
            themeProps={{ attribute: 'class', defaultTheme: 'dark' }}
          >
            <SidebarContextProvider>
              <ToastContextProvider>
                <ConfirmDialogContextProvider>
                  <>
                    <Toast />
                    <ConfirmDialog />
                    {children}
                  </>
                </ConfirmDialogContextProvider>
              </ToastContextProvider>
            </SidebarContextProvider>
          </NUIProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
