import { Inter } from 'next/font/google'

import NUIProvider from '@/context/next-ui-context'

import type { Metadata } from 'next'

import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: ' Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <NUIProvider themeProps={{ attribute: 'class', defaultTheme: 'dark' }}>
          {children}
        </NUIProvider>
      </body>
    </html>
  )
}
