import { Inter } from 'next/font/google'
import Script from 'next/script'

import Toast from '@/components/toast'

import { NextAuthProvider } from '@/context/next-auth-context'
import NUIProvider from '@/context/next-ui-context'
import { ToastContextProvider } from '@/context/toast-context'

import type { Metadata } from 'next'

import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: ' Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <head>
        <Script
          src="https://unpkg.com/@phosphor-icons/web"
          strategy="beforeInteractive"
        />
      </head>
      <body className={inter.className}>
        <NextAuthProvider>
          <NUIProvider
            themeProps={{ attribute: 'class', defaultTheme: 'dark' }}
          >
            <ToastContextProvider>
              <>
                <Toast />
                {children}
              </>
            </ToastContextProvider>
          </NUIProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
